// <auto-generated />
using System;
using Book2Screen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Book2Screen.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20240716124956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Book2Screen.Models.Actor", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("integer")
                        .HasColumnName("actors_id");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("ActorsId")
                        .HasName("actors_pkey");

                    b.HasIndex("MovieId");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Works")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("works");

                    b.HasKey("AuthorId")
                        .HasName("author_pkey");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("genre");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Orjlanguage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("orjlanguage");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("BookId")
                        .HasName("books_pkey");

                    b.HasIndex("AuthorId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CommentText")
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.HasKey("CommentId")
                        .HasName("comments_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .HasColumnType("integer")
                        .HasColumnName("director_id");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Works")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("works");

                    b.HasKey("DirectorId")
                        .HasName("directors_pkey");

                    b.ToTable("directors", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<double?>("Boxofficerevenue")
                        .HasColumnType("double precision")
                        .HasColumnName("boxofficerevenue");

                    b.Property<double?>("Budget")
                        .HasColumnType("double precision")
                        .HasColumnName("budget");

                    b.Property<int?>("DirectorId")
                        .HasColumnType("integer")
                        .HasColumnName("director_id");

                    b.Property<int?>("Movieduration")
                        .HasColumnType("integer")
                        .HasColumnName("movieduration");

                    b.Property<string>("Movietype")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("movietype");

                    b.Property<DateOnly?>("Releasedate")
                        .HasColumnType("date")
                        .HasColumnName("releasedate");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("MovieId")
                        .HasName("movies_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("DirectorId");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Mail")
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Book2Screen.Models.Actor", b =>
                {
                    b.HasOne("Book2Screen.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("actors_movie_id_fkey");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Book2Screen.Models.Book", b =>
                {
                    b.HasOne("Book2Screen.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("books_author_id_fkey");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Book2Screen.Models.Comment", b =>
                {
                    b.HasOne("Book2Screen.Models.Book", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .HasConstraintName("comments_book_id_fkey");

                    b.HasOne("Book2Screen.Models.User", "IdNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_user");

                    b.HasOne("Book2Screen.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("comments_movie_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("IdNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Book2Screen.Models.Movie", b =>
                {
                    b.HasOne("Book2Screen.Models.Book", "Book")
                        .WithMany("Movies")
                        .HasForeignKey("BookId")
                        .HasConstraintName("movies_book_id_fkey");

                    b.HasOne("Book2Screen.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .HasConstraintName("movies_director_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Book2Screen.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Book2Screen.Models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Book2Screen.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Book2Screen.Models.Movie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Book2Screen.Models.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
